### ISSUE TITLE
create_data method undefined

### ISSUE THREAD

**Issue by Mozijie255** [jplumail/people-counting#1]
The create_data in train.py line 74 cannot be resolved, where is it defined? See no import here too

**Comment by Mozijie255** [comment]
And I would appreciate it if code for generating tfrecords be provided, I just can't be sure how you serialize the Example

**Comment by jplumail** [comment]
You can generate the tfrecords with the `density_gen.py` script, just do `python density_gen.py` and it will create your TFRecords for the part B by default.
If you want TFRecords for part A also, you can modify this script.

**Comment by Mozijie255** [comment]
hard to reproduce the result, after more than 6000 epoches still can't get the result 
![1639819371(1)](https://user-images.githubusercontent.com/66461696/146636300-34d47a9d-8221-4e68-a65b-a6c5503aba41.png)
,

**Comment by jplumail** [comment]
Yes, I couldn't reproduce the results either unfortunately. I got an MAE of 30 I remember but couldn't get below 20 like they do in the paper...
If you find a way to make it better, please tell me !

**Comment by jplumail** [comment]
fixed issue in commit [#257](https://github.com/jplumail/people-counting/commit/25734e77da1e18ee8cdbe76c9ecfeef9da257835)
